### ISSUE TITLE
can't build example_buffered_serial_device against OF 0.9

### ISSUE THREAD

**Issue by avilleret** [bakercp/ofxSerial#7]
on Mac OS X 10.10.5 with of 0.9, after updating the example's Xcode project I got this error : 

~~~~
/Users/antoine/dev/of_v0.9.0_osx_release/addons/ofxSerial/libs/ofxSerial/src/SerialDeviceUtils.cpp:51:22: error: no type named 'RegularExpressionException' in namespace 'Poco'
        catch (Poco::RegularExpressionException& exception)
~~~~

**Comment by avilleret** [comment]
adding `#include "Poco/Exception.h"` on top of `SerialDeviceUtils.cpp` fixes this issue

**Comment by bakercp** [comment]
Also, are you using the develop branch?  It should be updated for 0.9.0.

**Comment by avilleret** [comment]
no I was using master branch, i'll give a try to develop branch asap

**Comment by bakercp** [comment]
Super!

**Comment by avilleret** [comment]
you're right, develop branch works fine with of 0.9
since of 0.9 is released, would you mind to merge develop branch into master ?
thanks

**Comment by bakercp** [comment]
Yes!  Thanks for checking.  I meant to do this before, but forgot.
